"""phase 5: voice turns

Revision ID: 00874856855b
Revises: b0882bbf0687
Create Date: 2026-09-06 12:58:02.561029
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '00874856855b'
down_revision: str | None = 'b0882bbf0687'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voice_turns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_message_id', sa.UUID(), nullable=True),
    sa.Column('assistant_message_id', sa.UUID(), nullable=True),
    sa.Column('llm_generation_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('audio_storage_key', sa.String(length=500), nullable=True),
    sa.Column('audio_content_type', sa.String(length=50), nullable=True),
    sa.Column('audio_provider', sa.String(length=100), nullable=True),
    sa.Column('audio_duration_ms', sa.Integer(), nullable=True),
    sa.Column('stage_latencies_ms', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'completed', 'partial', 'failed', 'interrupted')", name=op.f('ck_voice_turns_valid_status')),
    sa.ForeignKeyConstraint(['assistant_message_id'], ['turns.id'], name=op.f('fk_voice_turns_assistant_message_id_turns'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['llm_generation_id'], ['llm_generations.id'], name=op.f('fk_voice_turns_llm_generation_id_llm_generations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['conversation_sessions.id'], name=op.f('fk_voice_turns_session_id_conversation_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_message_id'], ['turns.id'], name=op.f('fk_voice_turns_user_message_id_turns'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_voice_turns'))
    )
    op.create_index(op.f('ix_voice_turns_session_id'), 'voice_turns', ['session_id'], unique=False)
    # NOTE: autogenerate also proposed dropping ix_knowledge_chunks_content_tsv
    # and ix_knowledge_chunks_embedding_cosine here - a false positive, since
    # both were created by hand via op.execute() in the Phase 4 migration
    # (functional/ivfflat indexes aren't expressible as plain SQLAlchemy
    # Index objects, so autogenerate's model-vs-DB diff doesn't know they're
    # intentional) and are still required by real retrieval - see
    # docs/rag.md. Deliberately not included.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_voice_turns_session_id'), table_name='voice_turns')
    op.drop_table('voice_turns')
    # ### end Alembic commands ###
