"""phase 6: guardrail evaluations, retrieval latency, raw model answer

Revision ID: 50c0eb6d9dda
Revises: 00874856855b
Create Date: 2026-09-06 14:15:17.747313
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '50c0eb6d9dda'
down_revision: str | None = '00874856855b'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guardrail_evaluations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('llm_generation_id', sa.UUID(), nullable=True),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('input_injection_detected', sa.Boolean(), nullable=False),
    sa.Column('input_injection_patterns', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('filtered_chunk_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_validation_issues', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('safety_flagged', sa.Boolean(), nullable=False),
    sa.Column('safety_categories', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('safety_method', sa.String(length=30), nullable=False),
    sa.Column('original_answer', sa.Text(), nullable=False),
    sa.Column('final_answer', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("decision IN ('approved', 'modified', 'blocked')", name=op.f('ck_guardrail_evaluations_valid_decision')),
    sa.ForeignKeyConstraint(['llm_generation_id'], ['llm_generations.id'], name=op.f('fk_guardrail_evaluations_llm_generation_id_llm_generations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['conversation_sessions.id'], name=op.f('fk_guardrail_evaluations_session_id_conversation_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guardrail_evaluations'))
    )
    op.create_index(op.f('ix_guardrail_evaluations_created_at'), 'guardrail_evaluations', ['created_at'], unique=False)
    op.create_index(op.f('ix_guardrail_evaluations_session_id'), 'guardrail_evaluations', ['session_id'], unique=False)
    # NOTE: autogenerate also proposed dropping ix_knowledge_chunks_content_tsv
    # and ix_knowledge_chunks_embedding_cosine here - the same known,
    # permanent false positive documented in docs/database.md and the
    # Phase 5 migration (both indexes were created by hand via op.execute()
    # in the Phase 4 migration and aren't in SQLAlchemy's model metadata).
    # Deliberately not included.
    # `server_default` on both new NOT NULL columns is required so this
    # migration is safe against tables that already have rows (same
    # reasoning as the Phase 2 migration's `audio_assets.kind` column).
    op.add_column(
        'llm_generations', sa.Column('raw_model_answer', sa.Text(), nullable=False, server_default='')
    )
    op.add_column(
        'retrieval_results', sa.Column('latency_ms', sa.Integer(), nullable=False, server_default='0')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('retrieval_results', 'latency_ms')
    op.drop_column('llm_generations', 'raw_model_answer')
    op.drop_index(op.f('ix_guardrail_evaluations_session_id'), table_name='guardrail_evaluations')
    op.drop_index(op.f('ix_guardrail_evaluations_created_at'), table_name='guardrail_evaluations')
    op.drop_table('guardrail_evaluations')
    # ### end Alembic commands ###
