"""phase 10 pipeline run delivery count

Revision ID: 64108f28672a
Revises: ac7cfe5d6818
Create Date: 2026-09-08 12:01:42.947648
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '64108f28672a'
down_revision: str | None = 'ac7cfe5d6818'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: autogenerate also proposed dropping ix_knowledge_chunks_content_tsv
    # and ix_knowledge_chunks_embedding_cosine here - the same known,
    # permanent false positive documented in docs/database.md and every
    # migration since Phase 4 (both indexes were created by hand via
    # op.execute() and aren't expressible in SQLAlchemy's model metadata).
    # Deliberately not included, same as every prior migration that hit
    # this.
    #
    # server_default='0' (not just the Python-side model default) so this
    # is safe to apply against a real, already-populated pipeline_runs
    # table, not only a fresh/empty one - every pre-existing row gets a
    # real, correct starting delivery_count of 0 (they were, definitionally,
    # never over-delivered before this column existed to count it).
    op.add_column('pipeline_runs', sa.Column('delivery_count', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pipeline_runs', 'delivery_count')
    # ### end Alembic commands ###
