"""phase 2: audio processing jobs, transcript/speaker/aligned segments, audio asset extensions

Revision ID: a1562e3cec5c
Revises: 581ec0529a9e
Create Date: 2026-09-05 23:35:09.543944
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'a1562e3cec5c'
down_revision: str | None = '581ec0529a9e'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aligned_turns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('speaker_label', sa.String(length=50), nullable=True),
    sa.Column('start_ms', sa.Integer(), nullable=False),
    sa.Column('end_ms', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['turns.id'], name=op.f('fk_aligned_turns_message_id_turns'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_aligned_turns'))
    )
    op.create_index(op.f('ix_aligned_turns_message_id'), 'aligned_turns', ['message_id'], unique=False)
    op.create_table('audio_processing_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('audio_asset_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('diarization_status', sa.String(length=20), nullable=True),
    sa.Column('diarization_error', sa.Text(), nullable=True),
    sa.Column('model_versions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('stage_durations_ms', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("diarization_status IS NULL OR diarization_status IN ('completed', 'unavailable', 'failed')", name=op.f('ck_audio_processing_jobs_valid_diarization_status')),
    sa.CheckConstraint("status IN ('pending', 'running', 'completed', 'failed')", name=op.f('ck_audio_processing_jobs_valid_status')),
    sa.ForeignKeyConstraint(['audio_asset_id'], ['audio_assets.id'], name=op.f('fk_audio_processing_jobs_audio_asset_id_audio_assets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['turns.id'], name=op.f('fk_audio_processing_jobs_message_id_turns'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['conversation_sessions.id'], name=op.f('fk_audio_processing_jobs_session_id_conversation_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audio_processing_jobs'))
    )
    op.create_index(op.f('ix_audio_processing_jobs_audio_asset_id'), 'audio_processing_jobs', ['audio_asset_id'], unique=False)
    op.create_index(op.f('ix_audio_processing_jobs_session_id'), 'audio_processing_jobs', ['session_id'], unique=False)
    op.create_table('speaker_segments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('speaker_label', sa.String(length=50), nullable=False),
    sa.Column('start_ms', sa.Integer(), nullable=False),
    sa.Column('end_ms', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('diarization_model_version', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['turns.id'], name=op.f('fk_speaker_segments_message_id_turns'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_speaker_segments'))
    )
    op.create_index(op.f('ix_speaker_segments_message_id'), 'speaker_segments', ['message_id'], unique=False)
    op.create_table('transcript_segments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('start_ms', sa.Integer(), nullable=False),
    sa.Column('end_ms', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('stt_model_version', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['turns.id'], name=op.f('fk_transcript_segments_message_id_turns'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transcript_segments'))
    )
    op.create_index(op.f('ix_transcript_segments_message_id'), 'transcript_segments', ['message_id'], unique=False)
    # server_default is set explicitly (not left to autogenerate) so this
    # column addition is safe even if audio_assets already has rows - every
    # existing row backfills to 'original', matching the ORM default.
    op.add_column(
        'audio_assets',
        sa.Column('kind', sa.String(length=20), nullable=False, server_default='original'),
    )
    op.add_column('audio_assets', sa.Column('source_asset_id', sa.UUID(), nullable=True))
    op.add_column('audio_assets', sa.Column('original_filename', sa.String(length=255), nullable=True))
    op.add_column('audio_assets', sa.Column('content_type', sa.String(length=100), nullable=True))
    op.add_column('audio_assets', sa.Column('size_bytes', sa.Integer(), nullable=True))
    op.add_column('audio_assets', sa.Column('channels', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_audio_assets_source_asset_id_audio_assets'), 'audio_assets', 'audio_assets', ['source_asset_id'], ['id'], ondelete='CASCADE')
    # Not detected by autogenerate (check-constraint diffing is off by
    # default) - added by hand to match the AudioAsset model.
    op.create_check_constraint('valid_kind', 'audio_assets', "kind IN ('original', 'processed')")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('valid_kind', 'audio_assets', type_='check')
    op.drop_constraint(op.f('fk_audio_assets_source_asset_id_audio_assets'), 'audio_assets', type_='foreignkey')
    op.drop_column('audio_assets', 'channels')
    op.drop_column('audio_assets', 'size_bytes')
    op.drop_column('audio_assets', 'content_type')
    op.drop_column('audio_assets', 'original_filename')
    op.drop_column('audio_assets', 'source_asset_id')
    op.drop_column('audio_assets', 'kind')
    op.drop_index(op.f('ix_transcript_segments_message_id'), table_name='transcript_segments')
    op.drop_table('transcript_segments')
    op.drop_index(op.f('ix_speaker_segments_message_id'), table_name='speaker_segments')
    op.drop_table('speaker_segments')
    op.drop_index(op.f('ix_audio_processing_jobs_session_id'), table_name='audio_processing_jobs')
    op.drop_index(op.f('ix_audio_processing_jobs_audio_asset_id'), table_name='audio_processing_jobs')
    op.drop_table('audio_processing_jobs')
    op.drop_index(op.f('ix_aligned_turns_message_id'), table_name='aligned_turns')
    op.drop_table('aligned_turns')
    # ### end Alembic commands ###
