"""phase 9 pipeline runs

Revision ID: ac7cfe5d6818
Revises: a52bd26346ed
Create Date: 2026-09-06 18:51:20.293031
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'ac7cfe5d6818'
down_revision: str | None = 'a52bd26346ed'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stage_name', sa.String(length=100), nullable=False),
    sa.Column('queue', sa.String(length=100), nullable=True),
    sa.Column('correlation_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('input_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('celery_task_id', sa.String(length=100), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'running', 'completed', 'failed')", name=op.f('ck_pipeline_runs_valid_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pipeline_runs'))
    )
    op.create_index(op.f('ix_pipeline_runs_correlation_id'), 'pipeline_runs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_created_at'), 'pipeline_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_stage_name'), 'pipeline_runs', ['stage_name'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_status'), 'pipeline_runs', ['status'], unique=False)
    # NOTE: autogenerate also proposed dropping ix_knowledge_chunks_content_tsv
    # and ix_knowledge_chunks_embedding_cosine here - the same known,
    # permanent false positive documented in docs/database.md and every
    # migration since Phase 4 (both indexes were created by hand via
    # op.execute() and aren't expressible in SQLAlchemy's model metadata).
    # Deliberately not included.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pipeline_runs_status'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_stage_name'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_created_at'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_correlation_id'), table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    # ### end Alembic commands ###
