"""phase 4: nlp, incongruence, memory, knowledge/RAG, llm generations

Revision ID: b0882bbf0687
Revises: 611aebcea854
Create Date: 2026-09-06 11:50:25.076992
"""
from __future__ import annotations

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'b0882bbf0687'
down_revision: str | None = '611aebcea854'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_summaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('covers_message_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('method', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['conversation_sessions.id'], name=op.f('fk_conversation_summaries_session_id_conversation_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation_summaries'))
    )
    op.create_index(op.f('ix_conversation_summaries_created_at'), 'conversation_summaries', ['created_at'], unique=False)
    op.create_index(op.f('ix_conversation_summaries_session_id'), 'conversation_summaries', ['session_id'], unique=False)
    op.create_table('knowledge_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('original_filename', sa.String(length=300), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'processing', 'completed', 'failed')", name=op.f('ck_knowledge_documents_valid_status')),
    sa.ForeignKeyConstraint(['session_id'], ['conversation_sessions.id'], name=op.f('fk_knowledge_documents_session_id_conversation_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_documents'))
    )
    op.create_index(op.f('ix_knowledge_documents_session_id'), 'knowledge_documents', ['session_id'], unique=False)
    op.create_table('knowledge_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('document_title', sa.String(length=300), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.Column('embedding_model', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], name=op.f('fk_knowledge_chunks_document_id_knowledge_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['conversation_sessions.id'], name=op.f('fk_knowledge_chunks_session_id_conversation_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_chunks'))
    )
    op.create_index(op.f('ix_knowledge_chunks_document_id'), 'knowledge_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_knowledge_chunks_session_id'), 'knowledge_chunks', ['session_id'], unique=False)
    # Approximate-nearest-neighbor index for vector search (cosine distance,
    # matching the `<=>` operator used in KnowledgeChunkRepository.search_vector).
    # `lists=10` is sized for demo/portfolio data volumes (hundreds-low
    # thousands of chunks), not production scale - see docs/rag.md.
    op.execute(
        "CREATE INDEX ix_knowledge_chunks_embedding_cosine ON knowledge_chunks "
        "USING ivfflat (embedding vector_cosine_ops) WITH (lists = 10)"
    )
    # Functional GIN index backing lexical search (to_tsvector/ts_rank_cd) -
    # no stored tsvector column: PostgreSQL full-text search computes
    # to_tsvector('english', content) at query time, matched against
    # plainto_tsquery(). See KnowledgeChunkRepository.search_lexical.
    op.execute(
        "CREATE INDEX ix_knowledge_chunks_content_tsv ON knowledge_chunks "
        "USING GIN (to_tsvector('english', content))"
    )
    op.create_table('nlp_annotations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('sentiment_label', sa.String(length=20), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=False),
    sa.Column('intent_label', sa.String(length=50), nullable=False),
    sa.Column('intent_confidence', sa.Float(), nullable=False),
    sa.Column('topics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('entities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_versions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['turns.id'], name=op.f('fk_nlp_annotations_message_id_turns'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nlp_annotations'))
    )
    op.create_index(op.f('ix_nlp_annotations_message_id'), 'nlp_annotations', ['message_id'], unique=False)
    op.create_table('retrieval_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('query_message_id', sa.UUID(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('embedding_model', sa.String(length=200), nullable=False),
    sa.Column('top_k', sa.Integer(), nullable=False),
    sa.Column('reranked', sa.Boolean(), nullable=False),
    sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['query_message_id'], ['turns.id'], name=op.f('fk_retrieval_results_query_message_id_turns'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['conversation_sessions.id'], name=op.f('fk_retrieval_results_session_id_conversation_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_retrieval_results'))
    )
    op.create_index(op.f('ix_retrieval_results_query_message_id'), 'retrieval_results', ['query_message_id'], unique=False)
    op.create_index(op.f('ix_retrieval_results_session_id'), 'retrieval_results', ['session_id'], unique=False)
    op.create_table('incongruence_signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('aligned_turn_id', sa.UUID(), nullable=False),
    sa.Column('incongruence_score', sa.Float(), nullable=False),
    sa.Column('semantic_signal', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('vocal_signal', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('signal_category', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("signal_category = 'analytical_not_diagnostic'", name=op.f('ck_incongruence_signals_valid_signal_category')),
    sa.ForeignKeyConstraint(['aligned_turn_id'], ['aligned_turns.id'], name=op.f('fk_incongruence_signals_aligned_turn_id_aligned_turns'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incongruence_signals'))
    )
    op.create_index(op.f('ix_incongruence_signals_aligned_turn_id'), 'incongruence_signals', ['aligned_turn_id'], unique=False)
    op.create_table('llm_generations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('query_message_id', sa.UUID(), nullable=False),
    sa.Column('answer_message_id', sa.UUID(), nullable=True),
    sa.Column('retrieval_result_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('context_token_estimate', sa.Integer(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_summary', sa.Text(), nullable=False),
    sa.Column('grounding_status', sa.String(length=20), nullable=False),
    sa.Column('grounding_details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("grounding_status IN ('grounded', 'partially_grounded', 'ungrounded', 'unavailable')", name=op.f('ck_llm_generations_valid_grounding_status')),
    sa.ForeignKeyConstraint(['answer_message_id'], ['turns.id'], name=op.f('fk_llm_generations_answer_message_id_turns'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['query_message_id'], ['turns.id'], name=op.f('fk_llm_generations_query_message_id_turns'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['retrieval_result_id'], ['retrieval_results.id'], name=op.f('fk_llm_generations_retrieval_result_id_retrieval_results'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['conversation_sessions.id'], name=op.f('fk_llm_generations_session_id_conversation_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_generations'))
    )
    op.create_index(op.f('ix_llm_generations_query_message_id'), 'llm_generations', ['query_message_id'], unique=False)
    op.create_index(op.f('ix_llm_generations_session_id'), 'llm_generations', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_llm_generations_session_id'), table_name='llm_generations')
    op.drop_index(op.f('ix_llm_generations_query_message_id'), table_name='llm_generations')
    op.drop_table('llm_generations')
    op.drop_index(op.f('ix_incongruence_signals_aligned_turn_id'), table_name='incongruence_signals')
    op.drop_table('incongruence_signals')
    op.drop_index(op.f('ix_retrieval_results_session_id'), table_name='retrieval_results')
    op.drop_index(op.f('ix_retrieval_results_query_message_id'), table_name='retrieval_results')
    op.drop_table('retrieval_results')
    op.drop_index(op.f('ix_nlp_annotations_message_id'), table_name='nlp_annotations')
    op.drop_table('nlp_annotations')
    op.execute("DROP INDEX IF EXISTS ix_knowledge_chunks_content_tsv")
    op.execute("DROP INDEX IF EXISTS ix_knowledge_chunks_embedding_cosine")
    op.drop_index(op.f('ix_knowledge_chunks_session_id'), table_name='knowledge_chunks')
    op.drop_index(op.f('ix_knowledge_chunks_document_id'), table_name='knowledge_chunks')
    op.drop_table('knowledge_chunks')
    op.drop_index(op.f('ix_knowledge_documents_session_id'), table_name='knowledge_documents')
    op.drop_table('knowledge_documents')
    op.drop_index(op.f('ix_conversation_summaries_session_id'), table_name='conversation_summaries')
    op.drop_index(op.f('ix_conversation_summaries_created_at'), table_name='conversation_summaries')
    op.drop_table('conversation_summaries')
    # ### end Alembic commands ###
